FROM alpine:3.21.4

RUN apk add --no-cache nginx

RUN apk add --no-cache --virtual .build-deps openssl && \
	mkdir -p /etc/nginx/ssl && \
	openssl req -x509 -nodes \
		-days 365 \
		-keyout /etc/nginx/ssl/inception.key \
		-out /etc/nginx/ssl/inception.crt \
		-subj "/CN=${DOMAIN_NAME}"

RUN mkdir -p /var/www/wordpress /var/run/nginx && \
	chmod 755 /var/www/wordpress && \
	chown -R nginx:nginx /var/www/wordpress

COPY conf/nginx.conf /etc/nginx/nginx.conf

CMD ["nginx", "-g", "daemon off;"]

